#version: "3.9"

services:
  proton-privoxy:
    build: .
    container_name: proton_privoxy_service
    
    cap_add:
      - NET_ADMIN             # Required for OpenVPN to modify network interfaces and routes
    # devices:                # Usually not needed if mknod in app/run works for /dev/net/tun
    #   - "/dev/net/tun:/dev/net/tun"
    
